apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  td-agent.conf: |
  <source>
  @type tail
  path /var/log/k8s/*.log
  pos_file /var/log/td-agent/httpd-access.log.pos
  tag k8s.log
  <parse>
    @type none
  </parse>
  </source>
  <match k8s.log>
  @type stdout
  <format>
    @type single_value
  </format>
  </match>
  
